spring:
  application:
    name: Frankfurter

server:
  port: 8080

frankfurter:
  api:
    base-url: https://api.frankfurter.app
    connection-timeout: 5000
    read-timeout: 5000

github:
  username: fahri-allobank
